# Do not change any values in this file
server:
  port: ${PORT:8080}

spring:
  datasource:
    hikari:
      maxLifetime: "1800000"
      connectionTimeout: "30000"
      idleTimeout: "600000"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    default: "local"
W